### ISSUE TITLE
Number as overlay blocks mouse clicks

### ISSUE THREAD

**Issue by Mikelol** [tomill/wow-KotmoguDebuff#1]
The number on the raid frames often blocks clicking on that person to target / use mouse over on them.

Solution:  Add settings to move, adjust, etc., the numbers debuff.  At the very least, add a click through or if you click the number it also targets that person.

**Comment by tomill** [comment]
ty report Mike, i ll try to fix this.

**Comment by Mikelol** [comment]
any updates?

**Comment by tomill** [comment]
soooon :tm: 

weekend at least :)

**Comment by tomill** [comment]
fixed. I just submitted to curseforge. please wait a minutes release on curse.com.

**Comment by Mikelol** [comment]
Hey man, saw the update and it works great!  Good job, keep it up
